# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import text_mate_pb2 as text__mate__pb2


class TextMateServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTextMatePlain = channel.unary_unary(
                '/textMate.TextMateService/GetTextMatePlain',
                request_serializer=text__mate__pb2.CodeSource.SerializeToString,
                response_deserializer=text__mate__pb2.MateData.FromString,
                )


class TextMateServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTextMatePlain(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TextMateServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTextMatePlain': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTextMatePlain,
                    request_deserializer=text__mate__pb2.CodeSource.FromString,
                    response_serializer=text__mate__pb2.MateData.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'textMate.TextMateService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TextMateService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTextMatePlain(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/textMate.TextMateService/GetTextMatePlain',
            text__mate__pb2.CodeSource.SerializeToString,
            text__mate__pb2.MateData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
